import 'stdlib'

# Class portage
#
#  Provides the core portage configuration and some common portage
#  tools.
#
# @author Gunnar Wrobel <p@rdus.de>
# @version 1.0
# @package tool_portage
#
class portage (
  $profile              = 
    "/usr/portage/profiles/default/linux/$::architecture/10.0",
  $use                  = false,
  $chost                = false,
  $cflags               = false,
  $accept_keywords      = false,
  $logdir               = false,
  $dispatch_conf_logdir = false,
  $overlays             = [],
  $fetch_command        = false,
  $mirrors              = [],
  $rsync_mirror         = false,
  $binhost              = false,
  $binhost_only         = false,
  $emerge_opts          = false,
  $make_opts            = false,
  $features             = [],
  $input_devices        = [],
  $video_devices        = [],
  $config_protect       = [],
  $config_protect_mask  = [],
  $linguas              = [],
  $eclass_warning       = false,
  $sysadmin_email       = false,
  $mailserver           = 'localhost',
  $mailfrom_user        = 'portage',
  $mailfrom_fqdn        = $::fqdn,
  $layman_storage       = false,
  $gpg_dir              = false,
  $gpg_key              = false,
) {
  
  include portage::config::backup
  include portage::config
  include portage::config::restore
  include portage::emerge
  
  $unstable_keyword = "~$::architecture"

#   portage::use_flags { 'eselect':
#     context => 'portage_common_eselect',
#     package => 'app-admin/eselect',
#     use     => 'doc bash-completion',
#     tag     => 'buildhost'
#   }
#   portage::use_flags { 'portage':
#     context => 'portage_common_portage',
#     package => 'sys-apps/portage',
#     use     => 'doc',
#     tag     => 'buildhost'
#   }
#   portage::keywords { 'esearch':
#     context => 'portage_esearch',
#     package => 'app-portage/esearch',
#     keywords => $unstable_keyword,
#     tag     => 'buildhost'
#   }
  portage::keywords { 'portage':
    context => 'portage',
    package => '=sys-apps/portage-2.2*',
    keywords => "**",
    tag     => 'buildhost'
  }
  portage::unmask { 'portage':
    context => 'portage',
    package => '=sys-apps/portage-2.2*',
    tag     => 'buildhost',
  }
  package {['eix', 'eselect', 'euses', 'gentoolkit', 'gentoolkit-dev',
            'mirrorselect', 'portage-utils']:
    ensure   => 'installed',
    require  => Package['portage'],
    tag      => 'buildhost',
  }
#   package {'esearch':
#     category => 'app-portage',
#     ensure   => 'installed',
#     require  => Portage::Keywords['esearch'],
#     tag      => 'buildhost',
#   }
#   package {'eselect':
#     category => 'app-admin',
#     ensure   => 'installed',
#     require  => Portage::Use_flags['eselect'],
#     tag      => 'buildhost',
#   }
  package { 'portage':
    category => 'sys-apps',
    ensure   => 'latest',
    require  => [Portage::Keywords['portage'], Portage::Unmask['portage']],
    tag      => 'buildhost',
  }

  if $logdir {
    file {'portage_logdir':
      path   => $logdir,
      ensure => 'directory',
      owner  => 'portage',
      group  => 'portage',
      tag    => 'buildhost'
    }
  }

  if $dispatch_conf_logdir {
    file {'dispatch_conf_logdir':
      path   => $dispatch_conf_logdir,
      ensure => 'directory',
      tag    => 'buildhost'
    }
  }

  # Portage configuration
  file {
    '/etc/make.profile':
      ensure  => 'link',
      target  => "..$profile",
      notify  => Exec['portage_changed_config'];
    
    '/etc/make.conf':
      content => template("portage/make.conf"),
      require => [Concat['/etc/portage/make.conf.puppet'], Package['portage']],
      notify  => Exec['portage_changed_config'],
      tag     => 'buildhost';
    
    '/etc/dispatch-conf.conf':
      content => template("portage/dispatch-conf.conf"),
      require => Package['portage'],
      tag     => 'buildhost';
    
    '/etc/config-archive':
      ensure  => 'directory',
      tag     => 'buildhost';
    
    '/etc/eix-sync.conf':
      content => '*',
      require => Package['eix'],
      tag     => 'buildhost';
    
    '/etc/cron.daily/eclean':
      source  => 'puppet:///modules/portage/eclean',
      mode    => 755;
    
    '/etc/cron.daily/eix-sync':
      source  => 'puppet:///modules/portage/eix-sync',
      mode    => 755;
    
    '/etc/cron.daily/glsa-check':
      content => template("portage/glsa-check"),
      mode    => 755;
    
    '/etc/logrotate.d/portage':
      source  => 'puppet:///modules/portage/logrotate.portage';
    
    '/usr/portage/distfiles':
      ensure  => 'directory';
  }
  
  concat { '/etc/portage/make.conf.puppet':
    require => Package['portage'],
    notify  => Exec['portage_changed_config'],
    tag     => 'buildhost',
  }

  concat::fragment { 'make_conf_puppet_header':
    target  => '/etc/portage/make.conf.puppet',
    content => "# Autogenerated by Puppet, do not edit\n\n",
    order   => 01,
  }

  if $gpg_dir {
    portage::make_conf_fragment { 'gpg_dir':
      value => "PORTAGE_GPG_DIR=\"$portage_gpg_dir\"",
      tag   => 'buildhost'
    }
  }

  if $gpg_key {
    portage::make_conf_fragment { 'gpg_key':
      value => "PORTAGE_GPG_KEY=\"$portage_gpg_key\"",
      tag   => 'buildhost'
    }
  }

  if $eclass_warning {
    portage::make_conf_fragment { 'eclass_warning':
      value => "PORTAGE_ECLASS_WARNING_ENABLE=\"0\""
    }
  }
}
